/**
 * Domain types for the World App Atlas.
 *
 * The dataset is a curated, public-knowledge view of dominant delivery and
 * service apps in each country. Where market share isn't precisely
 * documented, ranks are ordinal estimates (see notes in countryAppMap.ts).
 */

export type Category =
  | "food"
  | "ride"
  | "grocery"
  | "courier"
  | "fintech"
  | "streaming"
  | "superapp";

export interface CategoryMeta {
  id: Category;
  label: string;
  short: string;
  /** Tailwind-bound color token (also exported as a hex below for SVG fills). */
  hex: string;
}

export interface App {
  id: string;
  name: string;
  category: Category;
  /** Path to the SVG monogram in /public/logos. Generated by scripts/setup.mjs. */
  logo: string;
  /** Brand-leaning hex color used for marker fill, accent strokes, badges. */
  color: string;
  /** ISO 3166-1 alpha-3 of the company HQ. */
  hqCountry: string;
  /** 2-letter monogram drawn inside markers when the logo isn't loaded yet. */
  mark: string;
  /** True if this is the most-used app globally in its category. */
  flagshipForCategory?: boolean;
}

export interface CountryAppRanking {
  appId: string;
  rank: number;
  /** Optional ordinal market-share estimate. Marked as approximate. */
  marketShare?: number;
}

export interface CountryAppEntry {
  /** ISO 3166-1 alpha-3 (e.g. "USA", "PAK"). */
  countryIso: string;
  countryName: string;
  /** Approximate centroid in [longitude, latitude]. Used for marker projection. */
  centroid: [number, number];
  /** Population in millions, used to scale marker radius. */
  populationM: number;
  apps: CountryAppRanking[];
}

export interface CountryFeatureProperties {
  name: string;
}

/** Filter state — `null` means "show everything". */
export type CategoryFilter = Category | null;
